"""FEMA flood certificate PDF generator (Standard Flood Hazard
Determination Form / Form 086-0-32)."""
from __future__ import annotations

import io

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas


def generate_flood_cert(
    *,
    property_address: str,
    flood_zone: str = "X",
    firm_panel: str = "06037C1234F",
    firm_date: str = "2008-09-26",
    determination_date: str = "2025-01-22",
    determined_by: str = "CoreLogic Flood Services",
) -> tuple[bytes, dict]:
    """Generate a flood certificate PDF.

    A property is in a Special Flood Hazard Area (SFHA) when the zone
    designation is anything other than X, B, or C — i.e. flood insurance
    is mandatory in those zones.
    """
    sfha = flood_zone.upper() not in ("X", "X500", "B", "C")

    metadata = {
        "document_type":      "FLOOD_CERT",
        "flood_zone":         flood_zone,
        "sfha":               sfha,
        "determination_date": determination_date,
        "firm_panel":         firm_panel,
        "firm_date":          firm_date,
        "property_address":   property_address,
    }

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=LETTER)
    width, height = LETTER

    # Title
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, height - 50, "Standard Flood Hazard Determination Form")
    c.setFont("Helvetica", 9)
    c.drawString(40, height - 66, "FEMA Form 086-0-32")
    c.drawRightString(width - 40, height - 50, "OMB No. 1660-0040")

    # Property
    y = height - 110
    c.setFont("Helvetica-Bold", 10)
    c.drawString(40, y, "Section I — Loan Information")
    c.setFont("Helvetica-Bold", 9)
    c.drawString(40, y - 18, "Property Address")
    c.setFont("Helvetica", 10)
    for i, line in enumerate(property_address.split("\n")):
        c.drawString(40, y - 32 - i * 12, line)

    # Section II — flood determination
    fy = y - 100
    c.setFont("Helvetica-Bold", 10)
    c.drawString(40, fy, "Section II — Flood Insurance Rate Map (FIRM) Information")
    c.setFont("Helvetica-Bold", 9)
    c.drawString(40, fy - 20, "NFIP Map / FIRM Panel Number")
    c.setFont("Helvetica", 10)
    c.drawString(40, fy - 34, firm_panel)

    c.setFont("Helvetica-Bold", 9)
    c.drawString(280, fy - 20, "FIRM Panel Effective / Revised Date")
    c.setFont("Helvetica", 10)
    c.drawString(280, fy - 34, firm_date)

    c.setFont("Helvetica-Bold", 9)
    c.drawString(40, fy - 60, "Flood Zone")
    c.setFont("Helvetica-Bold", 13)
    c.drawString(40, fy - 76, flood_zone)

    c.setFont("Helvetica-Bold", 9)
    c.drawString(280, fy - 60, "Special Flood Hazard Area")
    c.setFont("Helvetica-Bold", 11)
    c.drawString(280, fy - 76, "Yes" if sfha else "No")

    # Section III — determination
    dy = fy - 130
    c.setFont("Helvetica-Bold", 10)
    c.drawString(40, dy, "Section III — Flood Hazard Determination")
    c.setFont("Helvetica-Bold", 9)
    c.drawString(40, dy - 20, "Determination Date")
    c.setFont("Helvetica", 10)
    c.drawString(40, dy - 34, determination_date)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(280, dy - 20, "Determined By")
    c.setFont("Helvetica", 10)
    c.drawString(280, dy - 34, determined_by)

    if sfha:
        c.setFont("Helvetica-Bold", 11)
        c.drawString(40, dy - 70,
                     "FLOOD INSURANCE IS REQUIRED FOR THIS PROPERTY.")
    else:
        c.setFont("Helvetica", 10)
        c.drawString(40, dy - 70,
                     "Property is NOT in a Special Flood Hazard Area.")

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(
        width / 2, 30,
        "Simulated flood determination generated by EDMS Simulator for testing.",
    )

    c.showPage()
    c.save()
    return buf.getvalue(), metadata
