"""Homeowners insurance binder PDF generator."""
from __future__ import annotations

import io
from typing import Optional

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas


def generate_hoi_binder(
    *,
    insured_name: str,
    property_address: str,
    policy_number: str = "HOI-2025-000001",
    effective_date: str = "2025-01-25",
    annual_premium: float = 1_800.0,
    dwelling_coverage: float = 575_000,
    contents_coverage: Optional[float] = None,
    liability_coverage: float = 300_000,
    carrier_name: str = "State Farm Insurance",
    mortgagee_name: str = "EDMS Lending LLC",
    mortgagee_address: str = "1 Bank Plaza, Anywhere, USA",
) -> tuple[bytes, dict]:
    """Generate a HOI declarations / binder PDF."""
    if contents_coverage is None:
        contents_coverage = round(dwelling_coverage * 0.50, 2)
    monthly_premium = round(annual_premium / 12, 2)

    metadata = {
        "document_type":      "HOI_BINDER",
        "annual_premium":     float(annual_premium),
        "monthly_premium":    monthly_premium,
        "carrier_name":       carrier_name,
        "policy_number":      policy_number,
        "dwelling_coverage":  float(dwelling_coverage),
        "contents_coverage":  float(contents_coverage),
        "liability_coverage": float(liability_coverage),
        "effective_date":     effective_date,
        "insured_name":       insured_name,
        "property_address":   property_address,
    }

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=LETTER)
    width, height = LETTER

    # Title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(40, height - 50, "Homeowners Insurance Binder")
    c.setFont("Helvetica", 11)
    c.drawString(40, height - 66, carrier_name)
    c.drawRightString(width - 40, height - 50, f"Policy Number: {policy_number}")
    c.drawRightString(width - 40, height - 66, f"Effective Date: {effective_date}")

    # Insured + property
    y = height - 110
    c.setFont("Helvetica-Bold", 9)
    c.drawString(40, y, "Insured")
    c.setFont("Helvetica", 10)
    c.drawString(40, y - 14, insured_name)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(40, y - 36, "Property Address")
    c.setFont("Helvetica", 10)
    for i, line in enumerate(property_address.split("\n")):
        c.drawString(40, y - 50 - i * 12, line)

    # Coverages
    cy = y - 110
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, cy, "Coverages")
    rows = [
        ("Dwelling (Coverage A)",    dwelling_coverage),
        ("Personal Property (C)",    contents_coverage),
        ("Personal Liability (E)",   liability_coverage),
    ]
    c.setFont("Helvetica", 10)
    for i, (label, amount) in enumerate(rows):
        c.drawString(40, cy - 18 - i * 14, label)
        c.drawRightString(width - 40, cy - 18 - i * 14, f"${amount:,.0f}")

    # Premium
    py = cy - 90
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, py, "Premium")
    c.setFont("Helvetica", 10)
    c.drawString(40, py - 18, "Annual Premium")
    c.drawRightString(width - 40, py - 18, f"${annual_premium:,.2f}")
    c.drawString(40, py - 32, "Monthly Payment")
    c.drawRightString(width - 40, py - 32, f"${monthly_premium:,.2f}")
    c.drawString(40, py - 46, "Policy Premium")
    c.drawRightString(width - 40, py - 46, f"${annual_premium:,.2f}")

    # Mortgagee clause
    my = py - 90
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, my, "Mortgagee Clause")
    c.setFont("Helvetica", 10)
    c.drawString(40, my - 16, mortgagee_name)
    c.drawString(40, my - 30, mortgagee_address)
    c.drawString(40, my - 44, "Its Successors And/Or Assigns As Their Interests May Appear")

    # Carrier line — extractor anchors on this
    c.setFont("Helvetica-Bold", 9)
    c.drawString(40, my - 80, "Carrier Name")
    c.setFont("Helvetica", 10)
    c.drawString(40, my - 94, carrier_name)

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(
        width / 2, 30,
        "Simulated HOI binder generated by EDMS Simulator for testing.",
    )

    c.showPage()
    c.save()
    return buf.getvalue(), metadata
