"""Property tax bill PDF generator (county assessor format)."""
from __future__ import annotations

import io
from typing import Optional

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas


def generate_tax_bill(
    *,
    property_address: str,
    owner_name: str,
    parcel_number: str = "123-456-789",
    tax_year: int = 2024,
    annual_tax: float = 7_200.0,
    land_value: float = 175_000,
    improvement_value: float = 400_000,
    payment_due_dates: Optional[list[str]] = None,
    county: str = "Sample County",
) -> tuple[bytes, dict]:
    """Generate a property tax bill PDF."""
    if payment_due_dates is None:
        payment_due_dates = [f"{tax_year}-12-10", f"{tax_year + 1}-04-10"]
    assessed_value = land_value + improvement_value

    metadata = {
        "document_type":     "PROPERTY_TAX_BILL",
        "assessed_value":    float(assessed_value),
        "land_value":        float(land_value),
        "improvement_value": float(improvement_value),
        "annual_tax":        float(annual_tax),
        "tax_year":          tax_year,
        "parcel_number":     parcel_number,
        "owner_name":        owner_name,
        "property_address":  property_address,
        "county":            county,
    }

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=LETTER)
    width, height = LETTER

    # Title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(40, height - 50, f"{county} Property Tax Bill")
    c.setFont("Helvetica", 10)
    c.drawString(40, height - 66, f"Tax Year {tax_year}")
    c.drawRightString(width - 40, height - 50, f"Parcel Number: {parcel_number}")

    # Owner + property
    y = height - 110
    c.setFont("Helvetica-Bold", 9)
    c.drawString(40, y, "Owner of Record")
    c.setFont("Helvetica", 10)
    c.drawString(40, y - 14, owner_name)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(40, y - 36, "Property Address")
    c.setFont("Helvetica", 10)
    for i, line in enumerate(property_address.split("\n")):
        c.drawString(40, y - 50 - i * 12, line)

    # Assessed values
    ay = y - 110
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, ay, "Assessed Values")
    rows = [
        ("Land Value",        land_value),
        ("Improvement Value", improvement_value),
        ("Assessed Value",    assessed_value),
    ]
    c.setFont("Helvetica", 10)
    for i, (label, amount) in enumerate(rows):
        c.drawString(40, ay - 18 - i * 14, label)
        c.drawRightString(width - 40, ay - 18 - i * 14, f"${amount:,.2f}")

    # Tax due
    ty = ay - 90
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, ty, "Tax Calculation")
    c.setFont("Helvetica", 10)
    c.drawString(40, ty - 18, "Annual Tax")
    c.drawRightString(width - 40, ty - 18, f"${annual_tax:,.2f}")
    c.drawString(40, ty - 32, "Total Tax")
    c.drawRightString(width - 40, ty - 32, f"${annual_tax:,.2f}")

    # Payment due dates
    py = ty - 80
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, py, "Payment Due Dates")
    c.setFont("Helvetica", 10)
    for i, dd in enumerate(payment_due_dates):
        c.drawString(40, py - 18 - i * 14,
                     f"Installment {i+1}:  {dd}   ${annual_tax / len(payment_due_dates):,.2f}")

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(
        width / 2, 30,
        "Simulated property tax bill generated by EDMS Simulator for testing.",
    )

    c.showPage()
    c.save()
    return buf.getvalue(), metadata
