"""Title commitment PDF generator (Schedule A / B-I / B-II)."""
from __future__ import annotations

import io
from typing import Optional

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas


def generate_title_commitment(
    *,
    property_address: str,
    legal_description: str = "Lot 12, Block 4, Sample Subdivision",
    estate_amount: float = 575_000,
    vestee_name: str = "James Q. Public",
    title_company: str = "First American Title",
    commitment_date: str = "2025-01-20",
    requirements: Optional[list[str]] = None,
    exceptions: Optional[list[str]] = None,
) -> tuple[bytes, dict]:
    """Generate a Schedule-A/B title commitment PDF."""
    if requirements is None:
        requirements = [
            "Pay off existing mortgage held by ABC Bank",
            "Record warranty deed conveying title to insured",
            "Pay property taxes through closing date",
        ]
    if exceptions is None:
        exceptions = [
            "Easement to utility company recorded 1998",
            "Restrictive covenants of subdivision",
            "Rights of parties in possession",
        ]

    metadata = {
        "document_type":      "TITLE_COMMITMENT",
        "property_address":   property_address,
        "commitment_date":    commitment_date,
        "estate_amount":      float(estate_amount),
        "title_company":      title_company,
        "requirements_count": len(requirements),
        "exceptions_count":   len(exceptions),
    }

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=LETTER)
    width, height = LETTER

    # Title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(40, height - 50, "Commitment for Title Insurance")
    c.setFont("Helvetica", 10)
    c.drawString(40, height - 66, title_company)
    c.drawRightString(width - 40, height - 50, f"Commitment Date: {commitment_date}")

    # Schedule A
    y = height - 110
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y, "SCHEDULE A")
    c.setFont("Helvetica-Bold", 9)
    c.drawString(40, y - 16, "1. Estate or Interest")
    c.setFont("Helvetica", 10)
    c.drawString(40, y - 30, "Fee Simple")
    c.setFont("Helvetica-Bold", 9)
    c.drawString(40, y - 50, "2. Amount of Insurance")
    c.setFont("Helvetica", 10)
    c.drawString(40, y - 64, f"${estate_amount:,.2f}")
    c.setFont("Helvetica-Bold", 9)
    c.drawString(40, y - 84, "3. Vestee")
    c.setFont("Helvetica", 10)
    c.drawString(40, y - 98, vestee_name)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(40, y - 118, "4. Property")
    c.setFont("Helvetica", 10)
    for i, line in enumerate(property_address.split("\n")):
        c.drawString(40, y - 132 - i * 12, line)
    c.drawString(40, y - 158, legal_description)

    # Schedule B-I requirements
    sy = y - 200
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, sy, "SCHEDULE B-I — Requirements")
    c.setFont("Helvetica", 10)
    for i, req in enumerate(requirements):
        c.drawString(40, sy - 18 - i * 14, f"{i+1}. {req}")

    # Schedule B-II exceptions
    ey = sy - 30 - len(requirements) * 14 - 20
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, ey, "SCHEDULE B-II — Exceptions")
    c.setFont("Helvetica", 10)
    for i, exc in enumerate(exceptions):
        c.drawString(40, ey - 18 - i * 14, f"{i+1}. {exc}")

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(
        width / 2, 30,
        "Simulated title commitment generated by EDMS Simulator for testing.",
    )

    c.showPage()
    c.save()
    return buf.getvalue(), metadata
