"""Driver's license JPG generator (Pillow).

Renders a state-card-style ID with name, DOB, address, DL#, expiry, and a
photo placeholder. Round-trip extraction will require OCR/vision in Phase C;
Phase B tests verify the image is well-formed and metadata is complete.
"""
from __future__ import annotations

import io
from datetime import date

from PIL import Image, ImageDraw, ImageFont


def _font(size: int):
    # PIL's default font is bitmap; for legibility scale up by drawing in
    # default and letting clients zoom. Returning default keeps no ttf dep.
    try:
        return ImageFont.truetype("arial.ttf", size)
    except OSError:
        return ImageFont.load_default()


def generate_drivers_license(
    *,
    state: str,
    full_name: str,
    dob: date,
    address: str,
    dl_number: str,
    expiry: date,
    sex: str = "M",
    height: str = "5'10\"",
    eyes: str = "BRN",
) -> tuple[bytes, dict]:
    width, height_px = 1010, 638  # 1.585:1 ID card aspect, 2x scale
    img = Image.new("RGB", (width, height_px), color=(245, 245, 248))
    draw = ImageDraw.Draw(img)

    # Top banner
    draw.rectangle([(0, 0), (width, 90)], fill=(28, 50, 110))
    draw.text((30, 18), state.upper(), fill=(255, 255, 255), font=_font(36))
    draw.text((30, 60), "DRIVER LICENSE", fill=(255, 220, 100), font=_font(20))

    # Photo placeholder (left column)
    photo_box = (40, 120, 280, 480)
    draw.rectangle(photo_box, outline=(120, 120, 120), width=2, fill=(220, 220, 230))
    cx = (photo_box[0] + photo_box[2]) // 2
    cy = (photo_box[1] + photo_box[3]) // 2
    draw.text((cx - 38, cy - 10), "PHOTO", fill=(120, 120, 120), font=_font(20))

    # Right column fields
    rx = 320
    label_color = (90, 90, 90)
    value_color = (10, 10, 30)
    fields = [
        ("DL", dl_number),
        ("EXP", expiry.isoformat()),
        ("LN", full_name.split()[-1]),
        ("FN", " ".join(full_name.split()[:-1]) or full_name),
        ("ADDRESS", address.replace("\n", ", ")),
        ("DOB", dob.isoformat()),
        ("SEX", sex),
        ("HGT", height),
        ("EYES", eyes),
    ]
    for i, (label, value) in enumerate(fields):
        y = 130 + i * 38
        draw.text((rx, y), f"{label}", fill=label_color, font=_font(14))
        draw.text((rx + 90, y - 2), str(value), fill=value_color, font=_font(18))

    # Footer
    draw.text(
        (30, height_px - 28),
        "Simulated identification — not a real driver's license. Generated by EDMS Simulator.",
        fill=(120, 120, 120),
        font=_font(12),
    )

    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=85)

    metadata = {
        "document_type": "DRIVERS_LICENSE",
        "state": state.upper(),
        "full_name": full_name,
        "dob": dob.isoformat(),
        "address": address,
        "dl_number": dl_number,
        "expiry": expiry.isoformat(),
        "sex": sex,
        "height": height,
        "eyes": eyes,
        "image_format": "JPEG",
        "image_size": img.size,
    }
    return buf.getvalue(), metadata
