"""Verify the AI-Vision extractor against the format-varied PDFs.

Picks one PDF per format variant generated by
``scripts/generate_realworld_simulation.py`` and runs Claude Vision on
each. Compares the extracted fields back to the meta.json (or sibling
JSON, for ``edms_pull``) ground-truth dict and reports per-field
accuracy.

This is a paid, key-gated check — without ``ANTHROPIC_API_KEY`` it
exits 0 with a "skipped" message so CI never breaks on it. Run it by
hand when you want to track extraction-accuracy regressions across
format variants:

    python scripts/verify_pdf_extraction.py
    python scripts/verify_pdf_extraction.py --max-pdfs 3   # cheaper smoke

Each call fans out N synchronous extracts. Each extract is one
Claude-Vision message with ``AI_EXTRACTION_MAX_PAGES`` PDF pages
attached as PNGs, so the bill scales linearly. Default ``--max-pdfs=8``
is one of each format family (3 W-2 + 3 bank + 1 credit + 1 appraisal)
which lands at ~25-30 cents per run on Sonnet 4.6.

The "samples" picker is deterministic: it walks the v2 tree, filters
for sibling-PDF doc types (W-2, paystub, bank, credit, appraisal,
title) plus loan ID, and takes the first match per (doc_type, format)
tuple so re-runs hit the same files."""
from __future__ import annotations

import argparse
import base64
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import pdf_formats   # noqa: E402


DEFAULT_ROOT = Path("local_storage/s3_simulation_v2")


def _doc_id_from_filename(name: str) -> str:
    """``EDMS-2026-LOAN-101-W2_CURRENT-D02-09.pdf.b64`` →
    ``EDMS-2026-LOAN-101-W2_CURRENT-D02-09``."""
    return name[: -len(".pdf.b64")] if name.endswith(".pdf.b64") else name


def _ground_truth_for(pdf_path: Path) -> dict | None:
    """Return the meta.json / sibling-JSON ground-truth fields for the
    PDF at ``pdf_path``. Returns None if no ground-truth record found.

    Three layout shapes:
    - email_inbox / borrower_portal / vendor_title: ``*_meta.json`` pair
    - edms_pull / vendor_*  / ai_chat: sibling ``{doc_id}.json``
    - los_encompass: doc_id is one of the entries in the batch JSON
    - shared_drive: no ground truth (synthetic UNKNOWN)
    """
    parent = pdf_path.parent
    channel = parent.name

    if channel == "shared_drive":
        return None

    if channel in ("email_inbox", "borrower_portal", "vendor_title"):
        # Strip the convention suffix used by the generator
        # (..._email.pdf.b64 / ..._upload.pdf.b64 / ..._title.pdf.b64).
        for suffix in ("_email", "_upload", "_title"):
            base = pdf_path.name[: -len(".pdf.b64")]
            if base.endswith(suffix):
                meta = parent / (base[: -len(suffix)] + suffix + "_meta.json")
                if meta.exists():
                    with meta.open() as f:
                        return json.load(f).get("extracted_fields", {})
        return None

    if channel == "los_encompass":
        # Doc id encoded in the .pdf.b64 filename; find the matching
        # entry inside the only batch.json sibling at that path's day.
        target_id = _doc_id_from_filename(pdf_path.name)
        for batch in parent.glob("*.json"):
            with batch.open() as f:
                docs = json.load(f)
            if not isinstance(docs, list):
                continue
            for d in docs:
                if d.get("document_id") == target_id:
                    return d.get("extracted_fields", {})
        return None

    # Default: edms_pull / vendor_equifax / vendor_corelogic / ai_chat
    sibling_json = parent / (pdf_path.name[: -len(".pdf.b64")] + ".json")
    if sibling_json.exists():
        with sibling_json.open() as f:
            d = json.load(f)
        return d.get("extracted_fields", {})
    return None


def _doc_type_and_los_for(pdf_path: Path) -> tuple[str, str]:
    """Recover ``(doc_type, los_id)`` from the file name. The generator
    encodes both: ``EDMS-2026-LOAN-101-W2_CURRENT-D02-09.pdf.b64``."""
    name = _doc_id_from_filename(pdf_path.name)
    # Trim per-channel suffix
    for suffix in ("_email", "_upload", "_title"):
        if name.endswith(suffix):
            name = name[: -len(suffix)]
            break
    parts = name.split("-")
    # Format is {PFX}-2026-LOAN-{NNN}-{DOC_TYPE}-D{day}-H{hour}[-suffix]
    los_id = "-".join(parts[2:4]) if len(parts) >= 4 else ""
    # doc_type spans from idx 4 up to the first part starting with 'D' + digits
    doc_type_parts = []
    for p in parts[4:]:
        if p.startswith("D") and p[1:].isdigit():
            break
        doc_type_parts.append(p)
    return "_".join(doc_type_parts), los_id


def pick_samples(root: Path, max_pdfs: int) -> list[Path]:
    """One PDF per (doc_type, format) tuple — first match wins so re-runs
    pick the same files. Limits the total to ``max_pdfs``."""
    seen: set[tuple[str, str | None]] = set()
    out: list[Path] = []
    for pdf in sorted(root.rglob("*.pdf.b64")):
        if pdf.parent.name == "shared_drive":
            continue
        doc_type, los_id = _doc_type_and_los_for(pdf)
        if not doc_type or not los_id:
            continue
        # Read ground truth FIRST so format_for can disambiguate bank
        # variants from bank_name.
        gt_for_fmt = _ground_truth_for(pdf) or {}
        fmt = pdf_formats.format_for(doc_type, los_id, "primary",
                                     fields=gt_for_fmt)
        if fmt is None:
            continue
        key = (doc_type, fmt)
        if key in seen:
            continue
        seen.add(key)
        out.append(pdf)
        if len(out) >= max_pdfs:
            break
    return out


def _accuracy_row(gt: dict, extracted: dict) -> tuple[int, int, list]:
    """Return ``(matches, total_gt_fields, missing_or_wrong_list)``.

    A field counts as a match when:
    - the key is present in ``extracted``
    - the value, coerced to a comparable form (string / numeric), equals
      the ground-truth value (numeric within 1% or string-equals after
      casefold)
    """
    matches, total = 0, 0
    misses = []
    for k, v in gt.items():
        if v is None or isinstance(v, bool) or v == "":
            continue
        total += 1
        ev = extracted.get(k)
        if ev is None:
            misses.append((k, v, "missing"))
            continue
        # Numeric comparison
        try:
            gv_f = float(v)
            ev_f = float(ev)
            if abs(gv_f - ev_f) <= max(1.0, abs(gv_f) * 0.01):
                matches += 1
                continue
            misses.append((k, v, ev))
            continue
        except (TypeError, ValueError):
            pass
        # String comparison
        if str(v).strip().casefold() == str(ev).strip().casefold():
            matches += 1
        else:
            misses.append((k, v, ev))
    return matches, total, misses


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root",     default=str(DEFAULT_ROOT))
    ap.add_argument("--max-pdfs", type=int, default=8,
                    help="cap the number of API calls (cost guard)")
    ap.add_argument("--paths",    nargs="*",
                    help="explicit list of pdf.b64 paths to test "
                         "(overrides automatic sampling)")
    args = ap.parse_args()

    if not os.getenv("ANTHROPIC_API_KEY"):
        print("ANTHROPIC_API_KEY not set — skipping live AI-Vision verification.")
        print("(All other parts of the pipeline are exercised by `make test`.)")
        return 0
    if os.getenv("ENABLE_AI_EXTRACTION", "true").lower() != "true":
        print("ENABLE_AI_EXTRACTION=false — skipping live verification.")
        return 0

    # Defer the import until after the key gate so CI / unit-test
    # invocations don't need anthropic installed.
    from core.documents.extractors.claude_extractor import (
        extract_with_claude_sync,
    )

    root = Path(args.root)
    if args.paths:
        samples = [Path(p) for p in args.paths]
    else:
        samples = pick_samples(root, args.max_pdfs)

    if not samples:
        print(f"No format-renderable PDFs found under {root}. "
              "Run `python scripts/generate_realworld_simulation.py` first.")
        return 1

    print(f"Verifying {len(samples)} PDFs against meta.json ground truth.\n")
    print(f"{'doc_type':<24}{'format':<14}{'pages':<7}{'fields':<10}{'accuracy':<10}{'sample_path'}")
    print("-" * 110)

    overall_match, overall_total = 0, 0
    for pdf_path in samples:
        doc_type, los_id = _doc_type_and_los_for(pdf_path)
        # Read ground truth FIRST so format_for can disambiguate bank
        # variants by reading bank_name from the meta record.
        gt = _ground_truth_for(pdf_path) or {}
        fmt = pdf_formats.format_for(doc_type, los_id, "primary",
                                     fields=gt) or "-"
        if not gt:
            print(f"{doc_type:<24}{fmt:<14}-      no ground-truth — skipping")
            continue

        pdf_bytes = base64.b64decode(pdf_path.read_text())
        extracted, conf = extract_with_claude_sync(pdf_bytes, doc_type)

        matches, total, _misses = _accuracy_row(gt, extracted)
        overall_match += matches
        overall_total += total
        pct = (matches / total * 100) if total else 0.0
        # PDF page count via pymupdf
        try:
            import fitz
            doc = fitz.open(stream=pdf_bytes, filetype="pdf")
            pages = doc.page_count
            doc.close()
        except Exception:
            pages = "?"
        short = ".../" + "/".join(pdf_path.parts[-3:])
        print(f"{doc_type:<24}{fmt:<14}{pages!s:<7}"
              f"{matches}/{total:<8}{pct:>5.1f}%    {short}")

    print("-" * 110)
    if overall_total:
        print(f"\n  OVERALL: {overall_match}/{overall_total} "
              f"({overall_match / overall_total * 100:.1f}%) field accuracy "
              f"across {len(samples)} PDFs.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
